// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvnG1TntpUBGhZfmhxIczSw7Cm5-LM6rM',
    appId: '1:451152347226:web:36ded2a14c07a3b6259863',
    messagingSenderId: '451152347226',
    projectId: 'radio-db-2c0ea',
    authDomain: 'radio-db-2c0ea.firebaseapp.com',
    databaseURL: 'https://radio-db-2c0ea-default-rtdb.firebaseio.com',
    storageBucket: 'radio-db-2c0ea.appspot.com',
    measurementId: 'G-HL1044M39X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKmXJcRbUFXqIOQi8DOWQLEXVxLzJxc5M',
    appId: '1:451152347226:android:ae349a945958b9ef259863',
    messagingSenderId: '451152347226',
    projectId: 'radio-db-2c0ea',
    databaseURL: 'https://radio-db-2c0ea-default-rtdb.firebaseio.com',
    storageBucket: 'radio-db-2c0ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCjy2ng7as51pU0A9IO3WaLBnqdwboJMs',
    appId: '1:451152347226:ios:2b1239c8db22a501259863',
    messagingSenderId: '451152347226',
    projectId: 'radio-db-2c0ea',
    databaseURL: 'https://radio-db-2c0ea-default-rtdb.firebaseio.com',
    storageBucket: 'radio-db-2c0ea.appspot.com',
    iosBundleId: 'com.example.radioTestPlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCjy2ng7as51pU0A9IO3WaLBnqdwboJMs',
    appId: '1:451152347226:ios:d97d72872dda3e92259863',
    messagingSenderId: '451152347226',
    projectId: 'radio-db-2c0ea',
    databaseURL: 'https://radio-db-2c0ea-default-rtdb.firebaseio.com',
    storageBucket: 'radio-db-2c0ea.appspot.com',
    iosBundleId: 'com.example.radioTestPlayer.RunnerTests',
  );
}
